/**
 * Loopback TLS servers for the probe executor's tests.
 *
 * The certificates in `certs/` are committed fixtures, regenerated by
 * `certs/generate.sh`. Their keys protect nothing — every server here binds
 * `127.0.0.1` and lives for the length of one test.
 *
 * Which fixture proves which failure class, and why some need no trust setup:
 * OpenSSL reports `CERT_HAS_EXPIRED` *before* it complains about an untrusted
 * chain, so `expired` reaches TLS_EXPIRED against the ordinary system store
 * (verified live). `self-signed` is untrusted by construction. Only
 * `wrong-name` needs its CA trusted, or the untrusted-chain error would mask
 * the name mismatch — see `trustFixtureCa`.
 */
import fs from 'node:fs';
import path from 'node:path';
import tls from 'node:tls';
import { fileURLToPath } from 'node:url';

const CERT_DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), 'certs');

export type FixtureCert = 'valid' | 'wrong-name' | 'self-signed' | 'expired';

export function readFixture(name: FixtureCert | 'ca', ext: 'crt' | 'key'): Buffer {
  return fs.readFileSync(path.join(CERT_DIR, `${name}.${ext}`));
}

export interface TlsFixtureServer {
  port: number;
  /** Connections accepted so far — how a test sees that no request was sent. */
  requests: () => number;
  close: () => Promise<void>;
}

/**
 * Starts an HTTPS-ish server presenting `cert`, bound to `127.0.0.1`.
 *
 * It speaks just enough HTTP to answer one request. The tests that use it are
 * about the handshake, so what matters is that it counts whether any request
 * byte ever arrived — the evidence that an unauthorised socket was torn down
 * before the probe could write its secret headers.
 */
export async function startTlsServer(cert: FixtureCert): Promise<TlsFixtureServer> {
  let requests = 0;
  const server = tls.createServer(
    { key: readFixture(cert, 'key'), cert: readFixture(cert, 'crt') },
    (socket) => {
      socket.once('data', () => {
        requests += 1;
        socket.end('HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nok');
      });
    },
  );
  // Without this an unauthorised client aborting the handshake emits an
  // unhandled 'error' on the server and fails the whole test file.
  server.on('tlsClientError', () => undefined);

  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const address = server.address();
  if (address === null || typeof address === 'string') throw new Error('no port');

  return {
    port: address.port,
    requests: () => requests,
    close: () =>
      new Promise<void>((resolve) => {
        server.close(() => resolve());
      }),
  };
}

/**
 * Trusts the fixture CA for this process, returning an undo.
 *
 * Global trust state, so it is set inside the one test that needs it and
 * restored immediately. `NODE_EXTRA_CA_CERTS` cannot be used instead: Node
 * reads it once at startup, long before any test runs.
 */
export function trustFixtureCa(): () => void {
  const previous = tls.getCACertificates('default');
  tls.setDefaultCACertificates([readFixture('ca', 'crt').toString()]);
  return () => tls.setDefaultCACertificates(previous);
}
